# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-11 11:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='slug',
            field=models.SlugField(blank=True, default='msg', max_length=255),
        ),
        migrations.AlterField(
            model_name='message',
            name='title',
            field=models.CharField(default='User', max_length=255),
        ),
    ]
