# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-11 11:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_bot', '0002_auto_20180211_1636'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['created']},
        ),
    ]
